project_id = "iagkylxqlartqokuiahf"

[functions.admin-create-employee]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.secure-admin-management]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.accept-terms]
verify_jwt = false

[functions.generate-integrity-report]
verify_jwt = false

[functions.iot-sensor-webhook]
verify_jwt = false
